### ISSUE TITLE
[Urgent]Cleavejs not apply multiple input element. Project is running.

### ISSUE THREAD

**Issue by khoanguyen2610** [nosir/cleave.js#175]
Hi.
I got problem, when i use one class for menu input element. Cleavejs just apply one input, not apply for all.
I think problem is "owner.element = document.querySelector(element);" at line 69
Can you check this issue.
Thank you.
![screenshot-jsfiddle net 2017-04-12 17-50-50](https://cloud.githubusercontent.com/assets/17254044/24954282/e56343ae-1fa8-11e7-91f1-84c448c966c2.png)

**Comment by barbedCoil** [comment]
Adding my 2 cents:  I found that when using a css class to apply format to a series of text fields that the 1st entry in the text field array of DOM elements is not getting pulled in correctly

`                    new Cleave(".time-input-4", {
                        numeral: true,
                        numeralDecimalScale: 4
                    });
`
I have 10 entries like this:
`
<input type="text" list="listRatesTE" class="rate time-col" />
`

The first entry in the array of fields will allow entry and format but I could not enter more than 3 digits otherwise the field would be wiped clean:  999.9999 works but 9,999.9999 wipes the field.

**Comment by khoapossible** [comment]
I found solution.
First i using jquery each to get all input element with "class_name" then i replace class with random string and apply Cleave to each element.

>  $('.format_number').each(function(){
        var t = Date.now() + Math.floor(Math.random() * 10000);
        var newClass = 'format_number-' + t;
        $(this).removeClass('format_number').addClass(newClass);

        if($('.' + newClass).length){
            var cleaveCustom = new Cleave('.' + newClass, {
                            numeral: true,
                            numeralPositiveOnly: true
            });
        }
    })

**Comment by nosir** [comment]
Yea, please check this: https://github.com/nosir/cleave.js/issues/138
I will update readme to add the guide.

**Comment by khoanguyen2610** [comment]
@nosir Thank bro, My issue was solved.
