### ISSUE TITLE
multiple same class element didn't work

### ISSUE THREAD

**Issue by xiangice** [nosir/cleave.js#209]
```
<input name="aaa" type="text" value="" class="input-number">
<input name="bbb" type="text" value="" class="input-number">
<input name="ccc" type="text" value="" class="input-number">

var cleave = new Cleave('.input-number', {`
           numeral: true
  });
````
just first input is working.

**Comment by nosir** [comment]
You need a loop to assign instance for each of them.
Basically each instance only applies to one input field, so you can run instance.getRawValue() to get raw value for specific input field.
Please check this: https://github.com/nosir/cleave.js/issues/138

**Comment by iofacture** [comment]
I really like your JS library. Its very straightforward, easy to understand, and for the most part easy to use, But this issue is more than a little annoying - I feel like this is something that should be addressed as it seems to be something that comes up for a lot of your users. Is there some fundamental design reason the library can't be made to handle this without requiring the end user to loop over their inputs?

**Comment by nosir** [comment]
@iofacture I will think about what's the best way to do this, issue created, thanks
