### ISSUE TITLE
Cursor position caculation issue

### ISSUE THREAD

**Issue by nosir** [nosir/cleave.js#219]
`5432| 9876` -> type 0, it gives `5432 |0987 6`, which should be `5432 0|987 6`

**Comment by bn-l** [comment]
At the moment, when you have a full input and you type a character the entire entry moves down. I think when you put the cursor back in the input and type, it should be in "insert mode" and overwrite the input rather than pushing the existing input down and deleting the end character. What do you think?

**Comment by kmestre** [comment]
Hi guys,
I'm using Cleave to date fields and I'm having issues on cursor positioning when removing a character in the input. No matter what is the digit that I remove, the cursor is jumping to the end of the input. 
Is there any fix or workaround for this issue?

Thanks!

**Comment by nosir** [comment]
Fxed release: https://github.com/nosir/cleave.js/releases/tag/v1.2.0
