### ISSUE TITLE
[Enhancement] Capitalize first letter

### ISSUE THREAD

**Issue by unclebrain** [nosir/cleave.js#278]
It would be great if along with the Uppercase and Lowercase options, there could be a Capitalize option that would do what the css style
`text-transform: capitalize;`
does. The css style only changes the visualisation, the backend will receive the input as it was typed, so cleave.js would be useful here.

**Comment by nosir** [comment]
Say you want to achieve `Axxxx Bxxxx Cxxxx`? 
Is there a user cases you can explain a bit?

**Comment by purplekrayons** [comment]
I came here looking for a similar feature.

My use case involves input fields for names, addresses, cities, etc -- any proper noun really.

**Comment by nosir** [comment]
@purplekrayons With react you are supposed to pass in the length for each block section.
How would you do that for names, addresses, etc cause they are not fixed value

**Comment by purplekrayons** [comment]
Why only support the use of block patterns? I feel like you are limiting cleave.js -- which is a brilliant piece of code by the way 👍 

In one of my projects, I have a need to capitalize the first letter of many input fields, as described above. Since I needed this to be more than a simple css visualization, I came in search of such an option -- turns out there isn't one with cleave.js.

I would like to suggest options for cleave.js that do not require the use of a block pattern, and offers some simple things for simple input fields -- such as capitalization -- it just feels like there should be.

Here's the solution ([JSFiddle](https://jsfiddle.net/9zfg79jy/)) I implemented (note im using jquery).

It would be nice if we could do something similar (with cleave.js) like:

```
var example1 = new Cleave('.example1', {
    capitalizeFirst: true
});

var example2 = new Cleave('.example2', {
    capitalizeEach: true
});
```

`<input class="example1">`
> user input: 123 coder drive
> result: 123 Coder drive

`<input class="example2">`
> user input: 123 coder drive
> result: 123 Coder Drive

**Comment by nosir** [comment]
Thanks for the demo and the briefing. 

Basically, the feature you request: by passing in `delimiter` and `text-transform`, the lib can transforms the text after separating the text by user passed in delimiters (space in your case).

I agree this is a great feature but it is totally different from what the lib is designed for.
As you can read from the name `cleave`, it is targeting to separate the text rather than do text transforming.

So I would prefer to keep the scope as current.

Well actually, you actually provided a good idea and I might start a new lib from that.

Cheers
