### ISSUE TITLE
Range of user block input

### ISSUE THREAD

**Issue by joshua-weber** [nosir/cleave.js#292]
With the cleave.js block set up we can define the number of spaces the user input needs to fill before the delimiter kicks in. What if we allow a user to enter a range of values, say they could enter between 1-3 values before the delimiter kicks in. How would that be done with cleave.js?

example: This would be ideal when working with measurements. Users could enter 1 inch or 100 inches before the delimiter kicks in (1-1/2" or 100-1/2")

kind of like maxBlockLength, or minBlockLength

**Comment by sorahn** [comment]
@joshua-weber did you find something else to do this? I'm trying to get this lib to work with ip addresses.

**Comment by dstoch** [comment]
I am also interested in the solution. Maybe it will be good to reopen this issue? ;)

**Comment by nosir** [comment]
Hey guys, basically you are looking to do range format.

I agree this could be a great feature but it is out of the scope of what the lib is designed for.
As you can read from the name cleave, it is targeting to separate the text then add delimiters rather than do block masking input with range, number, regx etc.

So I would prefer to keep the scope as current :)

Thanks

**Comment by sorahn** [comment]
@nosir Thanks for the response.

@dstoch fwiw, I just ended up using a text input, and [ip.isV4Format](https://github.com/indutny/node-ip) for validation.

**Comment by dudash** [comment]
If you're counting, I was hoping to cleave IP address input too.
