### ISSUE TITLE
Change event does not fire in IE11

### ISSUE THREAD

**Issue by laurent-addstones** [nosir/cleave.js#309]
Hello, running this jsfiddle on ie11, one can see that the change event of $('#amount') does not fire,
can you investigate ?

[https://jsfiddle.net/7ofgy91j/](url)

Thanks

**Comment by jpickwell** [comment]
The change event works in IE 11. The problem is that the event doesn't fire until the field loses focus (i.e., on blur).

From http://api.jquery.com/change/:

> The `change` event is sent to an element when its value changes. This event is limited to `<input>` elements, `<textarea>` boxes and `<select>` elements. For select boxes, checkboxes, and radio buttons, the event is fired immediately when the user makes a selection with the mouse, but for the other element types the event is deferred until the element loses focus.

This isn't specific to jQuery. See the [MDN `change` event page](https://developer.mozilla.org/en-US/docs/Web/Events/change).

If you want a `change` event to fire immediately, then switch to the [`input` event](https://developer.mozilla.org/en-US/docs/Web/Events/input).

**Comment by nosir** [comment]
@jpickwell Thanks
Yes, change events only fires when input loses focus.
This has nothing to do with either jQ or Cleave
