### ISSUE TITLE
Switching delimiters to 1.234,56?

### ISSUE THREAD

**Issue by lcvbeek** [nosir/cleave.js#334]
I have several numeral inputs beneath each other, with values ranging from thousands to fractions with decimals. Since I'm in the EU, I want to display numbers as 1.234,56. If I read the docs correctly, to do this requires setting numeralDecimalMark to `,`, and the delimiter to `.`.

However, when I set the numeralDecimalMark to a comma, it completely misreads the fraction values.

`0.9142857142857143` becomes `09,142,857,142,857,143` rather than `0,91`.

These are my options:
`{
numeral: true,
numericOnly: true,
numeralDecimalScale: 2,
numeralDecimalMark: ','
delimiter: '.',
stripLeadingZeroes: false,
}`

Did I miss something or is it really difficult to switch the delimiters?

FYI: I'm using React 16.3 and cleave.js 1.3.3

Thanks!

**Comment by nosir** [comment]
Sorry for the delayed response.
How the decimal mark works is: it has to have the correct decimal mark setup in the string so the lib can format it, that is to say, to make it show as `0,91`, `0,91xxx` has to be set as raw value, and when you call getRawValue, you will probably get `0,91` rather than `0.91`.

**Comment by Sergioamjr** [comment]
@lcvbeek thank you so much, you saved my time.

**Comment by nosir** [comment]
Archive this, cheers.
