### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by esomkin** [nosir/cleave.js#349]
Hi! I'am using your component and it is very useful for me. 

But I'am confusing some strange behaviour. For example, when I try to set rawValue, it show in console `RangeError: Maximum call stack size exceeded`. Here jsfiddle link, where I reproduce a problem https://jsfiddle.net/sLd8fpk5/2/. The second problem is when I try to delete some digit in input, cursor jump to the right side of input. For example, enter in jsfiddle `1234567`, then try to remove `2`. 

Why it happening? Can you explain or give me some advice?
Thank you in advance!

PS: I'am using documentation about React version of Cleave.js https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md

**Comment by nosir** [comment]
1. Because you call setRawValue in the change event, which will trigger change event again, which causes an infinite loop. Basically in change event callback, you shall just setState to update your view
2. There is an known issue, let's track it here: https://github.com/nosir/cleave.js/issues/350
Thanks
