### ISSUE TITLE
Web Browser Compatibility List

### ISSUE THREAD

**Issue by dragthor** [nosir/cleave.js#384]
Hello everyone.  Is there a web browser compatibility list somewhere?

**Comment by dragthor** [comment]
So far I tested the following and it looks good:

- FF 62
- Edge 38
- Chrome 67
- IE 11
- iPhone 5S, Safari 7

**Comment by danielriodejaneiro** [comment]
I just went back from Safari iOS 7 up to 11 and tested the phone validator.
Same works fine for Android from 4.3 onwards (Chrome, Firefox)

**Comment by nosir** [comment]
Hey, since there are React component and basic JS version, so they might cover different browser compatibility. `https://caniuse.com/#search=oninput`
Basically any browser supports onInput Event should just work.
We are experiencing some cursor moving issue on Android devices, particularly Samsung devices.
