### ISSUE TITLE
Outdated addons

### ISSUE THREAD

**Issue by julien-meichelbeck** [nosir/cleave.js#388]
Hello,

Is it possible to regenerate the `src/addons` files ?

`libphonenumber` is outdated and it prevents from entering valid phone numbers.

**Comment by mlutfy** [comment]
Is there a workaround?

I was hitting my head against `Error: [cleave.js] Please include phone-type-formatter.{country}.js lib`, because looking at the actual exception thrown, which says: `TypeError: "pps.root.Cleave.AsYouTypeFormatter is not a constructor"`

In a plain html page, I ended up loading `cleave.js/src/addons/phone-type-formatter.us.js` instead of `dist/addons/cleave-phone.i18n.js`.

**Comment by nosir** [comment]
@julien-meichelbeck I just released the latest version of phone lib addons: https://github.com/nosir/cleave.js/releases/tag/v1.4.6

@mlutfy this latest homepage are referring to the same file as `dist/addons/cleave-phone.i18n.js` and it works fine.

Please let me know if there's still problem

**Comment by julien-meichelbeck** [comment]
Thanks @nosir !
