### ISSUE TITLE
Doesn't format Finnish phone numbers

### ISSUE THREAD

**Issue by Kotpes** [nosir/cleave.js#48]
On demo example, when selecting FI, no formatting applied. Same with at least several other countries (GP, IR).

**Comment by trjiang** [comment]
Hey @Kotpes could you try the number in the original google libphonenumber demo:
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
Let us know how it is going, also it will be great if you can provide a Finnish test phone number.
Cheers.

**Comment by Kotpes** [comment]
`****AsYouTypeFormatter Results****
Char entered: 4 Output: 4
Char entered: 0 Output: 40
Char entered: 1 Output: 401
Char entered: 8 Output: 4018
Char entered: 7 Output: 40187
Char entered: 1 Output: 401871
Char entered: 8 Output: 4018718
Char entered: 0 Output: 40187180
Char entered: 2 Output: 401871802`
Apparently, it also doesn't do the formatting. 
How number should look like: +358 XXX XXX XXX, where +358 is an international country code that one can replace with 0 while calling within the country, but most people just dial XXX XXX XXX ), whilst calling from outside one has to dial +358 (not 0) XXX XXX XX). I hope it clears it up a bit.

**Comment by trjiang** [comment]
Okay, then looks like google phone lib would need the leading `0` to format Finnish national numbers.
In your case, either `+3584571234567` or `04571234567` got formatted correctly.

For me it makes sense, cause here in Australia, to dial a number within the country, the leading 0 is a must thing.

But as you said, most people in your country just dial XXX XXX XXX, I guess that will be considered as a non-standard input by the google phone lib.

I would suggest you either put a tip or just leave it (since user can still enter the non-standard number).

Will close this issue. We will keep following google lib to see if there is any update. Cheers.

**Comment by Kotpes** [comment]
Fair enough. Thanks!
