### ISSUE TITLE
4571 prefix visa card is not valid/identified

### ISSUE THREAD

**Issue by dimagimburg** [nosir/cleave.js#54]
Maybe it is not valid in real world I don't know, but I just typed it in and got not valid 
video: http://screencast.com/t/WLi4Piao

**Comment by trjiang** [comment]
Hey @dimagimburg in your video, the `visa` credit card type is identified, not sure what do you mean by `not valid`, or is it preventing you to enter more numbers after 4571?

**Comment by dimagimburg** [comment]
Hi! I don't know what terminology to use here but if you try to input 4576666888811112 for example the visa icon is black, but for 457**1**666888811112 (see the digit in bold) it is gray again, maybe it is not an issue and cards starting with 4571 are not identified/valid. :)

**Comment by trjiang** [comment]
Oh sorry didn't notice that. Turns out 4571 is a co-branded dankort card. Try here: https://jsfiddle.net/nosir/aLnhdf3z/ (the first example) you will see the type detected.

This type is not list in demo but in doc: https://github.com/nosir/cleave.js/blob/master/doc/options.md#oncreditcardtypechanged

Maybe you can just consider this type as visa in the callback if you feel like there's no need to distinguish this.

**Comment by dimagimburg** [comment]
Oh, great. It's not that I faced an issue with this or something, just randomly type numbers and randomly got into this type of number :smile: thanks!

**Comment by trjiang** [comment]
Lol, good tester!
