### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by rbhalla** [nosir/cleave.js#69]
As per https://github.com/nosir/cleave.js/issues/59 I am doing the following:

```import Cleave from 'cleave.js/dist/cleave-react';```

I am getting `window is not defined`.  I'm trying to use cleave.js with an app that does server side rendering, and not quite sure how to get around this.

I'd prefer not to make my webpack config specific for any libraries. Any ideas?

**Comment by nosir** [comment]
Thanks for reporting, server sider rendering is not supported at the moment, we will have a look at it.

**Comment by bchelli** [comment]
Would PR https://github.com/nosir/cleave.js/pull/86 fix the issue?

**Comment by nosir** [comment]
`window` is actually needed for the phone format lib, that's due to the closure context I injected here:
https://github.com/nosir/libphonenumber-country-metadata/blob/master/gulpfile.js#L72

I will first change that for all the phone-lib addons and merge PR https://github.com/nosir/cleave.js/pull/86.

**Comment by nosir** [comment]
Released in v0.7.0
