### ISSUE TITLE
Browserify doesn't seem to work

### ISSUE THREAD

**Issue by webchaz** [nosir/cleave.js#72]
We're using browserify and tried to get this work via npm and we receive the following error:

```[Error: Cannot find module 'babelify' from '/app/node_modules/cleave.js']```

I've tried also installing babelify within our project and then it gives the following error:

```[Error: Couldn't find preset "stage-0" relative to directory "/app/node_modules/cleave.js" while parsing file: /app/node_modules/cleave.js/src/Cleave.js]```

We're not using React, just Browserify.  Any suggestions?

Thanks

**Comment by trjiang** [comment]
This is not good, will fix it very soon!

**Comment by nosir** [comment]
Fix and released, please try the latest version.

**Comment by webchaz** [comment]
Works perfect.  Thanks a lot!

**Comment by nosir** [comment]
Cool.

Technically `babelify` and `browserify-shim` shouldn't be necessary, but since we put ReactJS component in the same repo 😷, it requires some settings to make it compatible with npm module usage.

So for browserify users, even though you are not using React or shim, you will still need to install `babelify` and `browserify-shim`.

Anyway, it works, so never mind. Updated the guide in README.

**Comment by nosir** [comment]
Update: you won't need to setup `babelify` and `browserify-shim` anymore, if you are not using es6 or shim.
